### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by ParthPatwalaTA** [gitbrent/PptxGenJS#408]
I'm trying to generate ppt and in callback just want to log the output. Using Node js.
```
pptx.save(`uploads/test0`, function (file)  {
    console.log(`Generated ${file}`);
});
```
It is showing me this error. :point_down: 
```
Generated uploads/test0.pptx
(node:10099) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at /home/user/Documents/demo/node-pptx/node_modules/pptxgenjs/dist/pptxgen.js:1774:73
(node:10099) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10099) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can't seem to generate file when I use a callback. Without callback, it is working and it is also generating a file.

**Comment by gitbrent** [comment]
Please see the node demo.  It has a working example of using a callback.

**Comment by ParthPatwalaTA** [comment]
I believe you are talking about [this](https://gitbrent.github.io/PptxGenJS/docs/usage-saving.html#nodejs) example. Which is exactly the same thing i'm doing here. Can you give me an example how you're managing callback while saving ppt?
