### ISSUE TITLE
TypeError: Cannot read property '0' of undefined (not able to plot charts for some data)

### ISSUE THREAD

**Issue by mayank9804** [gitbrent/PptxGenJS#572]
<pre>
const PPTXJS = require('pptxgenjs')
let pptx = new PPTXJS()

let labelss = ['Law&Govt&Politics', 'Business', 'News', 'Family & Parenting', 'Shopping', 'Technology & <br/> Computing', 'Sports', 'Uncategorized', 'Travel', 'Food & Drink', 'Pets', 'Arts&Entertainment', <br/> 'Unknown', 'Science', 'Hobbies&Interests', 'Automotive', 'Style&Fashion', 'Classifieds', 'Home&Garden', <br/> 'Health & Fitness', 'Blacklist', 'Education', 'Government', 'Personal Finance', 'Sports ', 'Telecom', <br/> 'Careers']

let arrDataRegions = [
    {
        name: 'CTR',
        labels: labelss,
        value: [100, 915, 200, 300, 200, 100, 200, 100, 610, 1851, 82, 1294, 20, 100, 4107, 142, 726, 191, 1844, 416, 99, 158, 4623, 68, 600, 727, 162]
    },
    {
        name: 'Conversions',
        labels: labelss,
        value: [1227594, 9615, 464641, 36568, 290, 1691, 381727, 11809, 610, 1851, 82, 1294, 36825, 10181, 4107, 142, 726, 191, 1844, 416, 99, 158, 4623, 68, 600, 727, 162]
    }
]

let opts = {
    x: 0.5, y: 0.6, w: 6.0, h: 3.0,
    barDir: 'column',
    catAxisLabelColor: 'CC0000',
    catAxisLabelFontFace: 'Helvetica Neue',
    catAxisLabelFontSize: 14,
    catAxisOrientation: 'maxMin',
}

let slide = pptx.addNewSlide()

slide.addChart(pptx.charts.BAR, arrDataRegions, opts);
pptx.save("DEMP.pptx")

</pre>

**Stack Trace**
<pre>
TypeError: Cannot read property '0' of undefined                                                                            
at <PATH>\node_modules\pptxgenjs\dist\pptxgen.min.js:2:61163                                  
at Array.forEach (<anonymous>)                                                                                          
at <PATH>\node_modules\pptxgenjs\dist\pptxgen.min.js:2:60909                                   
at new Promise (<anonymous>)                                                                                            
at Object.createExcelWorksheet (<PATH>\node_modules\pptxgenjs\dist\pptxgen.min.js:2:43215)     
at <PATH>\node_modules\pptxgenjs\dist\pptxgen.min.js:2:106980                                  
at Array.forEach (<anonymous>)                                                                                         
at M (<PATH>\node_modules\pptxgenjs\dist\pptxgen.min.js:2:106932)                              
at <PATH>\node_modules\pptxgenjs\dist\pptxgen.min.js:2:105680                                  
at Array.forEach (<anonymous>)
</pre>

I am trying to plot chart for this data, but it giving me above error.

It works fine for this data
<pre>
[
   {
	name  : 'Region 1',
	labels: ['May', 'June', 'July', 'August'],
	values: [26, 53, 100, 75]
   },
   {
	name  : 'Region 2',
        labels: ['May', 'June', 'July', 'August'],
	values: [43.5, 70.3, 90.1, 80.05]
    }
];

</pre>

but not with the above data. What probably is causing this issue?

**Comment by mayank9804** [comment]
I was using value instead of values
