### ISSUE TITLE
 my code gets error on line 'pptx.save (path);'

### ISSUE THREAD

**Issue by Natanielsr** [gitbrent/PptxGenJS#580]
I updated the package to the security fixes be applied, but now a i receive this error

Error:
`H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2
Number.isInteger=Number.isInteger||function(e){return"number"==typeof e&&isFinite(e)&&Math.floor(e)===e};var NODEJS=!1,APPJS=!1;if("undefined"!=typeof module&&module.exports&&"function"==typeof require&&"undefined"==typeof window)try{require.resolve("fs"),NODEJS=!0}catch(e){NODEJS=!1}else"undefined"!=typeof module&&module.exports&&"function"==typeof require&&"undefined"!=typeof window&&(APPJS=!0);if(NODEJS||APPJS)var gObjPptxColors=require("../dist/pptxgen.colors.js"),gObjPptxShapes=require("../dist/pptxgen.shapes.js");var PptxGenJS=function(){var o={chart:{name:"chart"},image:{name:"image"},line:{name:"line"},rect:{name:"rect"},text:{name:"text"},placeholder:{name:"placeholder"}},a={LAYOUT_4x3:{name:"screen4x3",width:9144e3,height:6858e3},LAYOUT_16x9:{name:"screen16x9",width:9144e3,height:5143500},LAYOUT_16x10:{name:"screen16x10",width:9144e3,height:5715e3},LAYOUT_WIDE:{name:"custom",width:12192e3,height:

TypeError: Cannot read property 'split' of undefined
    at H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:144463
    at Array.forEach (<anonymous>)
    at oe (H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:144163)
    at H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:35062
    at Array.forEach (<anonymous>)
    at Object.slideObjectToXml (H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:26524)
    at pe (H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:151527)
    at N (H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:88173)
    at PptxGenJS.save (H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\node_modules\pptxgenjs\dist\pptxgen.min.js:2:155310)
    at gerar (H:\Nataniel\Documents\codigos\liturgy-s-slideshow-creator\scripts\gerar-slides.js:64:8)`

[MY CODE IS HERE](https://github.com/Natanielsr/liturgy-s-slideshow-creator/blob/master/scripts/gerar-slides.js)

**Comment by gitbrent** [comment]
[Closing due to age]
